#include <string>

extern void checkReturnCode(int8_t code, const std::string& context);

#define CODE_SUCCESS        0
#define CODE_ERROR       1
#define CODE_CUDA_NOT_SUPPORTED 2
#define CODE_LOOPBACK_DIRECTORY_ERROR 3
#define CODE_GET_DIRECTORY_PATH_ERROR 4
#define CODE_ERROR_FRAME_PATH_NOT_FOUND 5
#define CODE_CREATE_DIRECTORY_FAILED 6
#define CODE_CREATE_NESTED_DIRECTORY_FAILED 7
#define CODE_CREATE_DVI_DIRECTORIES_FAILED 8
#define CODE_CREATE_LOOPBACK_DIRECTORY_FAILED 9
#define CODE_SET_SESSION_TIMESTAMP_FAILED 10
#define CODE_GET_CURRENT_TIMESTAMP_FAILED 11
#define CODE_GET_BASE_PATH_FOUND_FAILED 12
#define CODE_DVI_VIDEO_PATH_NOT_FOUND 13
#define CODE_DVI_ERROR_PATH_NOT_FOUND 14
#define CODE_INVALID_CHANNEL 15
#define CODE_LOOPBACK_PATH_NOT_FOUND 16
#define CODE_FS_ERROR 17
#define CODE_INITIALIZE_VELOCITY_DRIVER_FAILED 18
#define CODE_SET_MEMORY_CONTROL_FAILED 19
#define CODE_FLOW_CONTROL_FAILED 20
#define CODE_PRINT_VERSION_INFO_FAILED 21
#define CODE_CHECK_CARD_RESOLUTION_FAILED 22
#define CODE_CONFIGURE_ROUTING_VELOCITY_FAILED 23
#define CODE_ALLOCATE_MEMORY_BUFFER_FAILED 24
#define CODE_CARD_SELF_TEST_FAILED 25
#define CODE_PCI_CONTROL_FAILED 26
#define CODE_CLOSE_VELOCITY_DRIVER_FAILED 27
#define CODE_CLEANUP_FAILED 28
#define CODE_SET_FLOW_CONTROL_FAILED 29
#define CODE_INITIALIZE_VELOCITY_VIDEO_WRITERS_FAILED 30
#define CODE_RESTART_CARD_FAILED 31
#define CODE_VIDEO_CAPTURE_START_FAILED 32
#define CODE_STOP_VIDEO_CAPTURE_FAILED 33
#define CODE_RESET_STATISTICS_FAILED 34
#define CODE_PRINT_STATISTICS_FAILED 35
#define CODE_STOP_CARD_FAILED 36
#define CODE_VIDEO_WRITER_RELEASE_FAILED 37
#define CODE_DEALLOCATE_MEMORY_BUFFER_FAILED 38
#define CODE_RELEASE_RESOURCES_FAILED 39
#define CODE_START_TEST_LOOPBACK_FAILED 40
#define CODE_RELEASE_FPS_COUNTER_FAILED 41
#define CODE_STOP_FLICKER_DETECTION_FAILED 42
#define CODE_INITIALIZE_CARD_PROPERTIES_FAILED 43

#define CODE_DVI_MANAGER_START_FAILED 44
#define CODE_DVI_MANAGER_STOP_FAILED 45
#define CODE_DVI_MANAGER_PRINT_STATISTICS_FAILED 46
#define CODE_DVI_MANAGER_CHECK_RUNNING_FAILED 47
#define CODE_DVI_MANAGER_CHECK_CHANNEL_RUNNING_FAILED 48
#define CODE_DVI_MANAGER_INVALID_CHANNEL 49
#define CODE_DVI_MANAGER_INIT_DEVICE_FAILED 50
#define CODE_DVI_MANAGER_SET_FORMAT_DEVICE_FAILED 51
#define CODE_DVI_MANAGER_BUFFER_REQUEST_FAILED 52
#define CODE_DVI_MANAGER_QUERY_BUFFER_REQUEST_FAILED 53
#define CODE_DVI_MANAGER_DEVICE_MMAP_BUFFER_FAILED 54
#define CODE_DVI_MANAGER_START_STREAMING_FAILED 55
#define CODE_DVI_MANAGER_CLEANUP_FAILED 56
#define CODE_DVI_MANAGER_RESOLUTION_CHECK_FAILED 57
#define CODE_DVI_MANAGER_GET_DEVICE_TEMPERATURE_FAILED 58
#define CODE_RUN_MWCAP_INFO_FAILED 59
#define CODE_SIGNAL_PRESENT_NONE 60
#define CODE_SIGNAL_PRESENT_FAILED 61
#define CODE_DVI_MANAGER_DRAW_STATISTICS_FAILED 62
#define CODE_DVI_MANAGER_RESET_STATISTICS_FAILED 63
#define CODE_DVI_MANAGER_GET_CURRENT_TIMESTAMP_FAILED 64

#define CODE_START_FLICKER_DETECTION_FAILED 65

#define CODE_DVI_MANAGER_INSUFFICIENT_BUFFERS 66
#define CODE_DVI_MANAGER_BUFFER_QUEUE_FAILED 67
#define CODE_VIDEO_WRITER_OPEN_FAILED 68